/**
 * modelConfig.js
 * Maps each crop to its TFLite model filename, class labels,
 * Urdu translations, severity classification, and treatment recommendations.
 */

export const MODEL_CONFIG = {
  maize: {
    modelFile: 'maize.tflite',
    inputSize: 224,
    labels: [
      'fall armyworm',
      'grasshoper',
      'healthy',
      'leaf beetle',
      'leaf blight',
      'leaf spot',
      'streak virus',
    ],
    labelsUr: [
      'فال آرمی ورم',
      'ٹڈی',
      'صحت مند',
      'پتی کا بھنورا',
      'پتی کا جھلساؤ',
      'پتی کا دھبہ',
      'اسٹریک وائرس',
    ],
    severity: ['diseased', 'diseased', 'healthy', 'diseased', 'diseased', 'warning', 'diseased'],
  },

  potato: {
    modelFile: 'potato.tflite',
    inputSize: 224,
    labels: ['Early_Blight', 'Healthy', 'Late_Blight'],
    labelsUr: ['جلد آنے والا جھلساؤ', 'صحت مند', 'دیر سے آنے والا جھلساؤ'],
    severity: ['warning', 'healthy', 'diseased'],
  },

  rice: {
    modelFile: 'rice.tflite',
    inputSize: 224,
    labels: [
      'bacterial_leaf_blight',
      'blast',
      'brown_spot',
      'dead_heart',
      'downy_mildew',
      'hispa',
      'normal',
      'tungro',
    ],
    labelsUr: [
      'بیکٹیریل پتی کا جھلساؤ',
      'بلاسٹ',
      'بھورا دھبہ',
      'ڈیڈ ہارٹ',
      'ڈاؤنی ملڈیو',
      'ہسپا',
      'نارمل',
      'تنگرو',
    ],
    severity: [
      'diseased',
      'diseased',
      'warning',
      'diseased',
      'warning',
      'warning',
      'healthy',
      'diseased',
    ],
  },

  tomato: {
    modelFile: 'tomato.tflite',
    inputSize: 224,
    labels: [
      'Bacterial_spot',
      'Early_blight',
      'Late_blight',
      'Leaf_Mold',
      'Septoria_leaf_spot',
      'Spider_mites Two-spotted_spider_mite',
      'Target_Spot',
      'Tomato_Yellow_Leaf_Curl_Virus',
      'Tomato_mosaic_virus',
      'healthy',
      'powdery_mildew',
    ],
    labelsUr: [
      'بیکٹیریل دھبہ',
      'جلد آنے والا جھلساؤ',
      'دیر سے آنے والا جھلساؤ',
      'پتی کی پھپھوندی',
      'سیپٹوریا پتی کا دھبہ',
      'مکڑی کے کیڑے',
      'ٹارگٹ دھبہ',
      'ٹماٹر پیلا پتی مڑنا وائرس',
      'ٹماٹر موزیک وائرس',
      'صحت مند',
      'پاؤڈری ملڈیو',
    ],
    severity: [
      'diseased',
      'warning',
      'diseased',
      'warning',
      'warning',
      'warning',
      'warning',
      'diseased',
      'diseased',
      'healthy',
      'warning',
    ],
  },

  wheat: {
    modelFile: 'wheat.tflite',
    inputSize: 224,
    labels: [
      'Aphid',
      'Black Rust',
      'Blast',
      'Brown Rust',
      'Common Root Rot',
      'Fusarium Head Blight',
      'Healthy',
      'Leaf Blight',
      'Mildew',
      'Mite',
      'Septoria',
      'Smut',
      'Stem fly',
      'Tan spot',
      'Yellow Rust',
    ],
    labelsUr: [
      'افیڈ',
      'کالا زنگ',
      'بلاسٹ',
      'بھورا زنگ',
      'عام جڑ سڑن',
      'فیوزیریم سر جھلساؤ',
      'صحت مند',
      'پتی کا جھلساؤ',
      'ملڈیو',
      'مائیٹ',
      'سیپٹوریا',
      'سموٹ',
      'تنے کی مکھی',
      'ٹین دھبہ',
      'پیلا زنگ',
    ],
    severity: [
      'warning',
      'diseased',
      'diseased',
      'warning',
      'diseased',
      'diseased',
      'healthy',
      'warning',
      'warning',
      'warning',
      'warning',
      'diseased',
      'warning',
      'warning',
      'diseased',
    ],
  },
};

/** Recommendations keyed by severity */
export const RECOMMENDATIONS = {
  healthy: [
    'فصل کی باقاعدہ نگرانی جاری رکھیں',
    'آبپاشی کا مناسب شیڈول برقرار رکھیں',
    'احتیاطی فنگی سائیڈ اسپرے لگائیں',
    'کوئی بھی متاثرہ پتے فوری ہٹا دیں',
  ],
  warning: [
    'متاثرہ علاقے پر گہری نظر رکھیں',
    'تجویز کردہ فنگی سائیڈ علاج لگائیں',
    'پودوں کے درمیان ہوا کی گردش بہتر بنائیں',
    'اوپر سے پانی دینے سے گریز کریں',
    'متاثرہ پتے احتیاط سے ہٹا دیں',
  ],
  diseased: [
    'متاثرہ پودوں کو فوری الگ کریں',
    'مخصوص فنگی سائیڈ یا کیڑے مار دوا لگائیں',
    'شدید متاثرہ پودوں کو ہٹا کر تلف کریں',
    'اگر پھیلاؤ ہو تو زرعی ماہر سے رجوع کریں',
    'متاثرہ مواد کمپوسٹ کے لیے استعمال نہ کریں',
    'استعمال کے بعد اوزار جراثیم سے پاک کریں',
  ],
};

export const RECOMMENDATIONS_EN = {
  healthy: [
    'Continue regular monitoring of the crop',
    'Maintain proper irrigation schedule',
    'Apply preventive fungicide spray',
    'Remove any affected leaves immediately',
  ],
  warning: [
    'Keep a close eye on the affected area',
    'Apply recommended fungicide treatment',
    'Improve air circulation between plants',
    'Avoid overhead watering',
    'Carefully remove affected leaves',
  ],
  diseased: [
    'Isolate affected plants immediately',
    'Apply specific fungicide or pesticide',
    'Remove and destroy severely affected plants',
    'Consult an agricultural expert if spread continues',
    'Do not use affected material for composting',
    'Sanitize tools after use',
  ],
};
